version: '3'

services:

    prometheus:
        image: prom/prometheus:v2.47.2
        restart: always
        ports:
            - 127.0.0.1:9090:9090
        volumes:
            - prometheus:/home/config:ro
            - prometheus:/prometheus
            - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        networks:
            - backend

    grafana:
        image: grafana/grafana:10.1.5
        restart: always
        ports:
            - 127.0.0.1:3000:3000
        networks:
            - backend
        volumes:
            - grafana:/var/lib/grafana

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: 172.38.0.0/24

volumes:
    prometheus:
    grafana:


