version: '3'

services:

    prometheus:
        image: prom/prometheus:v2.25.2
        restart: always
        ports:
            - 9090:9090  # TODO: close this port after configuration
        volumes:
            - prometheus:/home/config:ro
            - prometheus:/prometheus
        networks:
            - backend

    grafana:
        image: grafana/grafana:7.5.1
        restart: always
        ports:
            - 3000:3000
        networks:
            - backend
        volumes:
            - grafana:/var/lib/grafana

networks:
    backend:
        ipam:
            driver: default
            config:
                - subnet: 172.38.0.0/24

volumes:
    prometheus:
    grafana:


