apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ping-listener
  name: ping-listener
spec:
  containers:
  - image: voje/ping-listener:0.0.1
    name: ping-listener
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: ping-listener
  name: svc-ping-listener
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: ping-listener
status:
  loadBalancer: {}

