version: "3.1"
services:
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: derp
  bench:
    image: voje/pgbench:0.0.1
    command: sleep inf
    environment:
      PGPASSWORD: derp

