apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: benchmark
  name: depl-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benchmark
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: benchmark
    spec:
      nodeSelector:
        hugepages: "true"
      containers:
      - image: voje/benchmark:0.1.1
        name: benchmark
        command:
          - sleep
          - inf
        securityContext:
            privileged: true
        resources:
          requests:
            memory: 1Gi
            cpu: 3.0
            hugepages-2Mi: 900Mi
          limits:
            cpu: 4.0
            hugepages-2Mi: 900Mi
      volumes:
      - name: hugepages-2mi
        emptyDir:
          medium: HugePages-2Mi
